name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for package-lock changes
        run: |
          if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q "package-lock.json"; then
            echo "✅ package-lock.json changes detected"
          fi

      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

      - name: Check file size limits
        run: |
          find . -name "*.js" -o -name "*.ts" -o -name "*.tsx" -o -name "*.jsx" | \
          xargs wc -l | \
          awk '$1 > 500 { print "⚠️ Large file detected: " $2 " (" $1 " lines)" }'

      - name: Run security audit
        run: npm audit --audit-level moderate

      - name: Check for TODO/FIXME comments
        run: |
          echo "🔍 Checking for TODO/FIXME comments..."
          grep -r --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
            -n "TODO\|FIXME\|XXX\|HACK" src/ || echo "✅ No TODO/FIXME comments found"
